/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractRouteImport } from './routes/contract'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as VerifyReceiptIdRouteImport } from './routes/verify/$receiptId'
import { Route as ApiV1ContractRouteImport } from './routes/api/v1/contract'
import { Route as ApiV1HealthRouteImport } from './routes/api/v1/health'
import { Route as ApiV1OpenapiDotjsonRouteImport } from './routes/api/v1/openapi[.]json'
import { Route as ApiV1ReadyRouteImport } from './routes/api/v1/ready'
import { Route as ApiV1RunsRouteImport } from './routes/api/v1/runs'
import { Route as AppGuardsIdRouteImport } from './routes/app/guards/$id'
import { Route as AppGuardsNewRouteImport } from './routes/app/guards/new'
import { Route as AppRunsIdRouteImport } from './routes/app/runs/$id'
import { Route as ApiV1AuthNonceRouteImport } from './routes/api/v1/auth/nonce'
import { Route as ApiV1AuthSessionRouteImport } from './routes/api/v1/auth/session'
import { Route as ApiV1AuthVerifyRouteImport } from './routes/api/v1/auth/verify'
import { Route as ApiV1HooksEventsRouteImport } from './routes/api/v1/hooks/events'
import { Route as ApiV1RunsIdEventsRouteImport } from './routes/api/v1/runs/$id/events'
import { Route as ApiV1RunsIdFinishRouteImport } from './routes/api/v1/runs/$id/finish'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyReceiptIdRoute = VerifyReceiptIdRouteImport.update({
  id: '/verify/$receiptId',
  path: '/verify/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ContractRoute = ApiV1ContractRouteImport.update({
  id: '/api/v1/contract',
  path: '/api/v1/contract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HealthRoute = ApiV1HealthRouteImport.update({
  id: '/api/v1/health',
  path: '/api/v1/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1OpenapiDotjsonRoute = ApiV1OpenapiDotjsonRouteImport.update({
  id: '/api/v1/openapi.json',
  path: '/api/v1/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1ReadyRoute = ApiV1ReadyRouteImport.update({
  id: '/api/v1/ready',
  path: '/api/v1/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunsRoute = ApiV1RunsRouteImport.update({
  id: '/api/v1/runs',
  path: '/api/v1/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuardsIdRoute = AppGuardsIdRouteImport.update({
  id: '/app/guards/$id',
  path: '/app/guards/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGuardsNewRoute = AppGuardsNewRouteImport.update({
  id: '/app/guards/new',
  path: '/app/guards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRunsIdRoute = AppRunsIdRouteImport.update({
  id: '/app/runs/$id',
  path: '/app/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthNonceRoute = ApiV1AuthNonceRouteImport.update({
  id: '/api/v1/auth/nonce',
  path: '/api/v1/auth/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSessionRoute = ApiV1AuthSessionRouteImport.update({
  id: '/api/v1/auth/session',
  path: '/api/v1/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthVerifyRoute = ApiV1AuthVerifyRouteImport.update({
  id: '/api/v1/auth/verify',
  path: '/api/v1/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1HooksEventsRoute = ApiV1HooksEventsRouteImport.update({
  id: '/api/v1/hooks/events',
  path: '/api/v1/hooks/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1RunsIdEventsRoute = ApiV1RunsIdEventsRouteImport.update({
  id: '/$id/events',
  path: '/$id/events',
  getParentRoute: () => ApiV1RunsRoute,
} as any)
const ApiV1RunsIdFinishRoute = ApiV1RunsIdFinishRouteImport.update({
  id: '/$id/finish',
  path: '/$id/finish',
  getParentRoute: () => ApiV1RunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/docs': typeof DocsRoute
  '/roadmap': typeof RoadmapRoute
  '/verify/$receiptId': typeof VerifyReceiptIdRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/contract': typeof ApiV1ContractRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/ready': typeof ApiV1ReadyRoute
  '/api/v1/runs': typeof ApiV1RunsRouteWithChildren
  '/app/guards/$id': typeof AppGuardsIdRoute
  '/app/guards/new': typeof AppGuardsNewRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/api/v1/auth/nonce': typeof ApiV1AuthNonceRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/auth/verify': typeof ApiV1AuthVerifyRoute
  '/api/v1/hooks/events': typeof ApiV1HooksEventsRoute
  '/api/v1/runs/$id/events': typeof ApiV1RunsIdEventsRoute
  '/api/v1/runs/$id/finish': typeof ApiV1RunsIdFinishRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/docs': typeof DocsRoute
  '/roadmap': typeof RoadmapRoute
  '/verify/$receiptId': typeof VerifyReceiptIdRoute
  '/app': typeof AppIndexRoute
  '/api/v1/contract': typeof ApiV1ContractRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/ready': typeof ApiV1ReadyRoute
  '/api/v1/runs': typeof ApiV1RunsRouteWithChildren
  '/app/guards/$id': typeof AppGuardsIdRoute
  '/app/guards/new': typeof AppGuardsNewRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/api/v1/auth/nonce': typeof ApiV1AuthNonceRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/auth/verify': typeof ApiV1AuthVerifyRoute
  '/api/v1/hooks/events': typeof ApiV1HooksEventsRoute
  '/api/v1/runs/$id/events': typeof ApiV1RunsIdEventsRoute
  '/api/v1/runs/$id/finish': typeof ApiV1RunsIdFinishRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contract': typeof ContractRoute
  '/docs': typeof DocsRoute
  '/roadmap': typeof RoadmapRoute
  '/verify/$receiptId': typeof VerifyReceiptIdRoute
  '/app/': typeof AppIndexRoute
  '/api/v1/contract': typeof ApiV1ContractRoute
  '/api/v1/health': typeof ApiV1HealthRoute
  '/api/v1/openapi.json': typeof ApiV1OpenapiDotjsonRoute
  '/api/v1/ready': typeof ApiV1ReadyRoute
  '/api/v1/runs': typeof ApiV1RunsRouteWithChildren
  '/app/guards/$id': typeof AppGuardsIdRoute
  '/app/guards/new': typeof AppGuardsNewRoute
  '/app/runs/$id': typeof AppRunsIdRoute
  '/api/v1/auth/nonce': typeof ApiV1AuthNonceRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/auth/verify': typeof ApiV1AuthVerifyRoute
  '/api/v1/hooks/events': typeof ApiV1HooksEventsRoute
  '/api/v1/runs/$id/events': typeof ApiV1RunsIdEventsRoute
  '/api/v1/runs/$id/finish': typeof ApiV1RunsIdFinishRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contract'
    | '/docs'
    | '/roadmap'
    | '/verify/$receiptId'
    | '/app/'
    | '/api/v1/contract'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/ready'
    | '/api/v1/runs'
    | '/app/guards/$id'
    | '/app/guards/new'
    | '/app/runs/$id'
    | '/api/v1/auth/nonce'
    | '/api/v1/auth/session'
    | '/api/v1/auth/verify'
    | '/api/v1/hooks/events'
    | '/api/v1/runs/$id/events'
    | '/api/v1/runs/$id/finish'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contract'
    | '/docs'
    | '/roadmap'
    | '/verify/$receiptId'
    | '/app'
    | '/api/v1/contract'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/ready'
    | '/api/v1/runs'
    | '/app/guards/$id'
    | '/app/guards/new'
    | '/app/runs/$id'
    | '/api/v1/auth/nonce'
    | '/api/v1/auth/session'
    | '/api/v1/auth/verify'
    | '/api/v1/hooks/events'
    | '/api/v1/runs/$id/events'
    | '/api/v1/runs/$id/finish'
  id:
    | '__root__'
    | '/'
    | '/contract'
    | '/docs'
    | '/roadmap'
    | '/verify/$receiptId'
    | '/app/'
    | '/api/v1/contract'
    | '/api/v1/health'
    | '/api/v1/openapi.json'
    | '/api/v1/ready'
    | '/api/v1/runs'
    | '/app/guards/$id'
    | '/app/guards/new'
    | '/app/runs/$id'
    | '/api/v1/auth/nonce'
    | '/api/v1/auth/session'
    | '/api/v1/auth/verify'
    | '/api/v1/hooks/events'
    | '/api/v1/runs/$id/events'
    | '/api/v1/runs/$id/finish'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractRoute: typeof ContractRoute
  DocsRoute: typeof DocsRoute
  RoadmapRoute: typeof RoadmapRoute
  VerifyReceiptIdRoute: typeof VerifyReceiptIdRoute
  AppIndexRoute: typeof AppIndexRoute
  ApiV1ContractRoute: typeof ApiV1ContractRoute
  ApiV1HealthRoute: typeof ApiV1HealthRoute
  ApiV1OpenapiDotjsonRoute: typeof ApiV1OpenapiDotjsonRoute
  ApiV1ReadyRoute: typeof ApiV1ReadyRoute
  ApiV1RunsRoute: typeof ApiV1RunsRouteWithChildren
  AppGuardsIdRoute: typeof AppGuardsIdRoute
  AppGuardsNewRoute: typeof AppGuardsNewRoute
  AppRunsIdRoute: typeof AppRunsIdRoute
  ApiV1AuthNonceRoute: typeof ApiV1AuthNonceRoute
  ApiV1AuthSessionRoute: typeof ApiV1AuthSessionRoute
  ApiV1AuthVerifyRoute: typeof ApiV1AuthVerifyRoute
  ApiV1HooksEventsRoute: typeof ApiV1HooksEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contract': {
      id: '/contract'
      path: '/contract'
      fullPath: '/contract'
      preLoaderRoute: typeof ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$receiptId': {
      id: '/verify/$receiptId'
      path: '/verify/$receiptId'
      fullPath: '/verify/$receiptId'
      preLoaderRoute: typeof VerifyReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/contract': {
      id: '/api/v1/contract'
      path: '/api/v1/contract'
      fullPath: '/api/v1/contract'
      preLoaderRoute: typeof ApiV1ContractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/health': {
      id: '/api/v1/health'
      path: '/api/v1/health'
      fullPath: '/api/v1/health'
      preLoaderRoute: typeof ApiV1HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/openapi.json': {
      id: '/api/v1/openapi.json'
      path: '/api/v1/openapi.json'
      fullPath: '/api/v1/openapi.json'
      preLoaderRoute: typeof ApiV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/ready': {
      id: '/api/v1/ready'
      path: '/api/v1/ready'
      fullPath: '/api/v1/ready'
      preLoaderRoute: typeof ApiV1ReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runs': {
      id: '/api/v1/runs'
      path: '/api/v1/runs'
      fullPath: '/api/v1/runs'
      preLoaderRoute: typeof ApiV1RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/guards/$id': {
      id: '/app/guards/$id'
      path: '/app/guards/$id'
      fullPath: '/app/guards/$id'
      preLoaderRoute: typeof AppGuardsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/guards/new': {
      id: '/app/guards/new'
      path: '/app/guards/new'
      fullPath: '/app/guards/new'
      preLoaderRoute: typeof AppGuardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/runs/$id': {
      id: '/app/runs/$id'
      path: '/app/runs/$id'
      fullPath: '/app/runs/$id'
      preLoaderRoute: typeof AppRunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/nonce': {
      id: '/api/v1/auth/nonce'
      path: '/api/v1/auth/nonce'
      fullPath: '/api/v1/auth/nonce'
      preLoaderRoute: typeof ApiV1AuthNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/session': {
      id: '/api/v1/auth/session'
      path: '/api/v1/auth/session'
      fullPath: '/api/v1/auth/session'
      preLoaderRoute: typeof ApiV1AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/verify': {
      id: '/api/v1/auth/verify'
      path: '/api/v1/auth/verify'
      fullPath: '/api/v1/auth/verify'
      preLoaderRoute: typeof ApiV1AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/hooks/events': {
      id: '/api/v1/hooks/events'
      path: '/api/v1/hooks/events'
      fullPath: '/api/v1/hooks/events'
      preLoaderRoute: typeof ApiV1HooksEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/runs/$id/events': {
      id: '/api/v1/runs/$id/events'
      path: '/$id/events'
      fullPath: '/api/v1/runs/$id/events'
      preLoaderRoute: typeof ApiV1RunsIdEventsRouteImport
      parentRoute: typeof ApiV1RunsRoute
    }
    '/api/v1/runs/$id/finish': {
      id: '/api/v1/runs/$id/finish'
      path: '/$id/finish'
      fullPath: '/api/v1/runs/$id/finish'
      preLoaderRoute: typeof ApiV1RunsIdFinishRouteImport
      parentRoute: typeof ApiV1RunsRoute
    }
  }
}

interface ApiV1RunsRouteChildren {
  ApiV1RunsIdEventsRoute: typeof ApiV1RunsIdEventsRoute
  ApiV1RunsIdFinishRoute: typeof ApiV1RunsIdFinishRoute
}

const ApiV1RunsRouteChildren: ApiV1RunsRouteChildren = {
  ApiV1RunsIdEventsRoute: ApiV1RunsIdEventsRoute,
  ApiV1RunsIdFinishRoute: ApiV1RunsIdFinishRoute,
}

const ApiV1RunsRouteWithChildren = ApiV1RunsRoute._addFileChildren(
  ApiV1RunsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractRoute: ContractRoute,
  DocsRoute: DocsRoute,
  RoadmapRoute: RoadmapRoute,
  VerifyReceiptIdRoute: VerifyReceiptIdRoute,
  AppIndexRoute: AppIndexRoute,
  ApiV1ContractRoute: ApiV1ContractRoute,
  ApiV1HealthRoute: ApiV1HealthRoute,
  ApiV1OpenapiDotjsonRoute: ApiV1OpenapiDotjsonRoute,
  ApiV1ReadyRoute: ApiV1ReadyRoute,
  ApiV1RunsRoute: ApiV1RunsRouteWithChildren,
  AppGuardsIdRoute: AppGuardsIdRoute,
  AppGuardsNewRoute: AppGuardsNewRoute,
  AppRunsIdRoute: AppRunsIdRoute,
  ApiV1AuthNonceRoute: ApiV1AuthNonceRoute,
  ApiV1AuthSessionRoute: ApiV1AuthSessionRoute,
  ApiV1AuthVerifyRoute: ApiV1AuthVerifyRoute,
  ApiV1HooksEventsRoute: ApiV1HooksEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
